# Generated by Django 4.2.5 on 2023-12-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sobrenome", models.CharField(max_length=50)),
                ("data_nascimento", models.DateField()),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("rg", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=128, unique=True)),
                ("show", models.BooleanField(default=True)),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        default="Paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
            },
        ),
        migrations.CreateModel(
            name="Telefone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=15)),
                ("tipo", models.CharField(max_length=10)),
                (
                    "id_pessoa",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telefone",
                "verbose_name_plural": "Telefones",
            },
        ),
        migrations.CreateModel(
            name="Prontuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(blank=True, upload_to="")),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "id_pessoa",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.pessoa",
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prontuarios",
                "verbose_name_plural": "Prontuarios",
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(blank=True, max_length=30)),
                ("numero", models.CharField(blank=True, max_length=5)),
                ("bairro", models.CharField(blank=True, max_length=30)),
                ("cidade", models.CharField(blank=True, max_length=30)),
                ("uf", models.CharField(blank=True, max_length=2)),
                ("complemento", models.CharField(blank=True, max_length=30)),
                (
                    "id_pessoa",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereco",
                "verbose_name_plural": "Enderecos",
            },
        ),
        migrations.CreateModel(
            name="Credencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registro", models.CharField(max_length=12, unique=True)),
                ("data_de_inscricao", models.DateField()),
                ("especialidade", models.CharField(max_length=50)),
                ("situacao", models.CharField(max_length=10)),
                (
                    "id_pessoa",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial",
                "verbose_name_plural": "Credenciais",
            },
        ),
    ]
