# Generated by Django 4.2.5 on 2023-09-06 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.departamento",
            ),
        ),
    ]
