# Generated by Django 4.2.5 on 2023-09-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_alter_pessoa_departamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="crm",
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
